export const DESC_OBJ: Record<string, string> = {
    "rgb": "RGB is a color model that represents colors as mixtures of three underlying components — red, green, and blue color channels — that create various hues when combined.",
    "rgb()": "The rgb() functional notation expresses a color in the sRGB color space according to its red, green, and blue components. An optional alpha component represents the color's transparency.",
    "srgb": "The sRGB color space, or \"Standard RGB\", is the standard RGB (red, green, blue) color space. It was created to be used on monitors, printers, and the Web. It is the most widely used color space and is supported by most operating systems, software programs, monitors, and printers. sRGB is based on r, g, and b, with in-gamut values ranging from 0 to 1. The whitepoint is D65.",
    "srgb-linear": "The predefined linear-light sRGB color space, srgb-linear, is the same as srgb except that the transfer function is linear-light with no gamma-encoding. The srgb-linear color space accepts the three r, g, and b values as numeric parameters, with in-gamut colors ranging from 0 to 1. The whitepoint is D65.",
    "display-p3": "Defined by Apple, the Display P3, color space combines the DCI-P3 color gamut, the D65 whitepoint, and sRGB gamma curve. It is a wide gamut space typical of current wide-gamut monitors, enabling more vibrant greens and reds than the sRGB color gamut. The display-p3 space is based on r, g, and b channels, with in-gamut values ranging from 0 to 1. The whitepoint is D65.",
    "display-p3-linear": "The display-p3-linear predefined color space is similar to display-p3, except that it uses a linear-light transfer function and has no gamma-encoding, which allows for a higher precision in the colors displayed. The display-p3-linear space is based on r, g, and b channels, with in-gamut values ranging from 0 to 1. The whitepoint is D65.",
    "a98-rgb": "The Adobe® 1998 RGB color space designed to represent all the CMYK colors as RGB. About 50% of the visible colors specified by the CIELab color space can be achieved, encompassing more cyan-green hues than other RGB color spaces. In-gamut r, g, and b values range from 0 to 1. The transfer curve is a gamma function, close to but not exactly 1/2.2. The whitepoint is D65.",
    "prophoto-rgb": "Developed by Kodak, the prophoto-rgb color space can represent all the colors likely to occur in nature and about 90% of CIElab colors. In-gamut r, g, and b values range from 0 to 1. The transfer curve is a gamma function, with a value of 1/1.8, and a small linear portion near black. The whitepoint is D50, the same one used by CIELab.",
    "rec2020": "rec2020 is a broadcast industry standard for ultra-high definition 4k and 8k televisions. The ultra-wide gamut space is capable of representing almost all visible real-world colors, beyond the capabilities of most current displays. Coverage is expected to increase over time as displays improve. In-gamut r, g, and b values range from 0 to 1. The whitepoint is D65.",
    "cielab": "The CIELAB (or CIELab) color space, also referred to as L*a*b* (or Lab* for short), represents the entire range of color that humans can see. This color space was defined by International Commission on Illumination (CIE). It expresses color as three values: L* for perceptual lightness, and a* and b* for the four unique colors of human vision: red, green, blue, and yellow.",
    "lab()": "Based on lab-d50 colorspace, the lab() functional notation expresses a given color in the CIE L*a*b* color space. Lab represents the entire range of colors that humans can see by specifying the color's lightness, a red/green axis value, a blue/yellow axis value, and an optional alpha transparency value.",
    "lch()": "Based on lab-d50 colorspace, the lch() functional notation expresses a given color using the LCH color space, which represents lightness, chroma, and hue. It uses the same L axis as the lab() color function of the CIELab color space, but it uses the polar coordinates C (Chroma) and H (Hue).",
    "oklab()": "Based on lab-d65 colorspace, the oklab() functional notation expresses a given color in the Oklab color space, which attempts to mimic how color is perceived by the human eye. Oklab is a perceptual color space and is useful to: Transform an image to grayscale, without changing its lightness. Modify the saturation of colors, while keeping user perception of hue and lightness Create smooth and uniform gradients of colors (when interpolated manually, for example, in a <canvas> element). oklab() works with a Cartesian coordinate system on the Oklab color space — a- and b-axes. It can represent a wider range of colors than RGB, including wide-gamut and P3 colors. If you want a polar color system, chroma and hue, use oklch().",
    "oklch()": "Based on lab-d65 colorspace, the oklch() functional notation expresses a given color in the Oklab color space. oklch() is the cylindrical form of oklab(), using the same L axis, but with polar Chroma (C) and Hue (h) coordinates.",
    "xyz": "While combinations of red, green, and blue work well for representing colors on screen, sRGB doesn't directly correspond to how humans perceive color. Created by the International Commission on Illumination (CIE) in 1931, the CIE 1931 XYZ (or XYZ for short) color spaces are the first defined quantitative links between distributions of wavelengths in the electromagnetic visible spectrum and perceived colors in human vision. People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimuli of the three kinds of cone cells which, in principle, describe every visible color. The Y channel represents the luminance of a color. The Z channel reflects the amount of blue in the color but is not the same as the B in RGB. The X axis is orthogonal to the Y- and Z- axis of the XYZ color 3D coordinate system.",
    "xyz-d50": "xyz-d50 is the same as xyz-d65 except it uses D50 as the whitepoint.",
    "xyz-d65": "The xyz identifier is a synonym for the xyz-d65 color space. The axes are not limited to a 0 to 1 range as the color space is not bound to this range; these values are only used as reference points in defining percentage inputs and outputs. The whitepoint is D65."
};